export type Lang = "en" | "pt";

export const dict = {
  en: {
    app: {
      name: "Jev Playground",
      tagline: "Typed decisions in milliseconds",
      subtitle:
        "Compose a state and typed questions, run them against the Jev System One model via OpenRouter, and read calibrated probabilities with latency, tokens and cost.",
    },
    top: {
      langLabel: "Language",
      langEn: "EN",
      langPt: "PT",
      github: "Source",
      docs: "Jev docs",
      keyBadge: "Key",
      noKey: "No key",
    },
    gate: {
      title: "Connect your OpenRouter key",
      sub: "Paste a key to unlock the playground. It is validated against OpenRouter and kept only in this browser.",
      label: "OpenRouter API key",
      placeholder: "sk-or-v1-…",
      validate: "Validate key",
      validating: "Validating…",
      openrouterLink: "Get a key at openrouter.ai/keys",
      safety: "Create a key with a credit limit. Never reuse a production key here.",
      stored: "Stored in localStorage only. Nothing is sent anywhere except OpenRouter.",
      errorInvalid: "OpenRouter rejected this key. Check it and try again.",
      errorNetwork: "Could not reach the key endpoint. Retry in a moment.",
      errorEmpty: "Enter a key first (starts with sk-or-v1-).",
      connected: "Key connected",
      continueAnyway: "Skip validation and open the builder",
    },
    keyStatus: {
      label: "Label",
      remaining: "Credit left",
      limit: "Credit cap",
      usage: "Usage",
      freeTier: "Free tier",
      yes: "yes",
      no: "no",
      unlimited: "unlimited",
      change: "Change key",
      forget: "Forget key",
    },
    builder: {
      stateTitle: "State",
      stateHint: "The content to judge: a message, ticket, log line or JSON object.",
      stateModeText: "Text",
      stateModeJson: "JSON",
      statePlaceholderText: "Checkout shows a white screen after clicking Pay.",
      statePlaceholderJson: '{\n  "ticket": "Checkout shows a white screen after clicking Pay.",\n  "channel": "email"\n}',
      questionsTitle: "Questions",
      questionsHint: "All questions run in parallel against the same state. Split compound questions.",
      addNoul: "Add yes/no",
      addChoice: "Add choice",
      addScore: "Add score",
      emptyTitle: "No questions yet",
      emptyBody: "Add a yes/no, choice or score question to get a decision.",
      qId: "Key",
      qIdHint: "Answer id. Blank uses q1, q2…",
      qInstructions: "Question",
      qInstructionsPlaceholderNoul: "Does the customer report a defect?",
      qInstructionsPlaceholderChoice: "Which team should handle it?",
      qInstructionsPlaceholderScore: "How urgent is this?",
      noulName: "Yes / No (noul)",
      noulDesc: "Probability of yes, 0 to 1.",
      choiceName: "Choice",
      choiceDesc: "One option of up to 255, with full distribution.",
      scoreName: "Score",
      scoreDesc: "Ordered scale of 2 to 10 levels, weighted average.",
      criteriaOptional: "Criteria (optional)",
      criteriaTrue: "Close to 1 means",
      criteriaFalse: "Close to 0 means",
      criteriaOption: "Rubric for",
      optionKey: "Option",
      optionRubric: "Rubric (optional)",
      addOption: "Add option",
      removeOption: "Remove option",
      levels: "Levels (low to high)",
      levelPlaceholder: "Blocking revenue right now",
      addLevel: "Add level",
      removeLevel: "Remove level",
      removeQuestion: "Remove question",
      advancedTitle: "Advanced",
      modelLabel: "Model",
      sessionId: "session_id (optional)",
      sessionIdHint: "Groups requests in observability. Max 256 chars.",
      userId: "user (optional)",
      userIdHint: "End-user id for observability. Max 256 chars.",
    },
    issues: {
      title: "Request check",
      clean: "Ready to run",
      errors: "errors",
      warnings: "warnings",
      tips: "tips",
      stateEmpty: "State is empty. Add the content the model should judge.",
      stateInvalidJson: "State is not valid JSON. Fix the syntax or switch to Text mode.",
      stateTooLarge: "State exceeds the 32k token budget for state plus longest question. Trim it.",
      stateRot: "Large states with irrelevant detail degrade accuracy. Keep only what matters.",
      noQuestions: "Add at least one question.",
      duplicateId: "Duplicate answer key \"{{id}}\". Keys must be unique.",
      instructionsEmpty: "The question text is empty.",
      asksForText: "Jev never generates text. Turn the expectation into a choice among listed options.",
      compoundQuestion: "Two questions in one line. Split into separate questions: they run in parallel at no latency cost.",
      mathOrDates: "This looks like counting, math or date logic. Compute it in code and put the result in the state.",
      choiceNoOptions: "Choice needs at least one option.",
      choiceTooMany: "Choice accepts at most {{max}} options.",
      choiceDuplicateOption: "Duplicate option key. Option keys must be unique.",
      choiceNoExit: "Consider an \"other\" / \"none\" option so the model is not forced into a wrong class.",
      scoreLevelCount: "Score needs between {{min}} and {{max}} ordered levels.",
      scoreNumericLevels: "Numeric levels score badly. Describe a concrete situation per level.",
    },
    run: {
      run: "Run decisions",
      running: "Running…",
      again: "Run again",
      needsKey: "Connect a key to run",
      fixErrors: "Fix the errors to run",
      thresholdNote: "Bands: auto at 0.90, human review 0.50 to 0.89, abstain below 0.50.",
    },
    results: {
      title: "Decisions",
      emptyTitle: "No run yet",
      emptyBody: "Run the request to see typed answers, distributions and confidence.",
      decision: "Decision",
      probability: "Probability of yes",
      confidence: "Confidence",
      certainty: "Certainty",
      confidenceNote: "Confidence describes the distribution, not guaranteed correctness.",
      weighted: "Weighted score",
      distribution: "Distribution",
      rawAnswer: "Raw answer",
      bandAuto: "auto",
      bandHitl: "review",
      bandAbstain: "abstain",
      bandAutoHint: "Confidence at or above 0.90: safe to act automatically.",
      bandHitlHint: "Confidence 0.50 to 0.89: confirm with a human before acting.",
      bandAbstainHint: "Below 0.50: do not act. Escalate to a slower, deeper model.",
    },
    metrics: {
      title: "Metrics",
      latency: "Latency",
      inputTokens: "Input tokens",
      outputTokens: "Output tokens",
      cost: "Cost",
      perDecision: "Per decision",
      throughput: "Throughput",
      resolvedModel: "Resolved model",
      provider: "Provider",
      generationId: "Generation id",
      questionCount: "Questions",
      history: "Run history",
      historyHint: "Last runs in this browser. Latency bars, newest first.",
      clearHistory: "Clear",
      noHistory: "No runs recorded yet.",
      stats: "Generation stats",
      statsFetch: "Fetch generation stats",
      statsHint: "Reads GET /api/v1/generation with the id from the response body.",
    },
    inspector: {
      title: "Request",
      hint: "JSON body, request model, cURL and Postman export of the exact request.",
      tabBody: "JSON body",
      tabModel: "Request model",
      tabCurl: "cURL",
      tabPostman: "Postman",
      copy: "Copy",
      copied: "Copied",
      download: "Download collection",
      postmanHint: "Imports into Postman as a v2.1 collection. The key ships as the {{openrouter_api_key}} variable.",
      curlHint: "Uses the OPENROUTER_API_KEY environment variable.",
      modelIntro: "POST to the Decisions endpoint. Every field below is what this playground sends.",
      modelFields: [
        { field: "model", desc: "typesafe/jev-1.13 or the ~typesafe/jev-latest alias." },
        { field: "state", desc: "string, object or array of text. Judged once, shared by all questions." },
        { field: "questions", desc: "Map of id to question. All questions are evaluated in parallel." },
        { field: "questions.*.type", desc: "noul (probability of yes), choice (one of N), score (weighted level)." },
        { field: "questions.*.instructions", desc: "The full question. The map key never reaches the model." },
        { field: "questions.*.criteria", desc: "noul: optional {true, false} strings. choice: option to rubric (string or null). score: 2 to 10 ordered level descriptions." },
        { field: "session_id", desc: "Optional, max 256 chars. Groups requests in observability." },
        { field: "user", desc: "Optional, max 256 chars. End-user id for observability." },
      ],
    },
    errors: {
      network: "Network error. Retry, or check whether a proxy or extension is blocking the call.",
      e400: "Invalid request. The message names the field to fix.",
      e401: "Key missing or invalid. Check your OpenRouter key.",
      e402: "Out of credits. Top up at openrouter.ai/credits.",
      e403: "Forbidden for this key.",
      e404: "Not found. Check the model id.",
      e413: "Payload too large. Shrink the state.",
      e422: "Validation failed.",
      e429: "Rate limited. Wait a moment and retry.",
      e5xx: "OpenRouter or TypeSafe is overloaded. Retry shortly.",
      generic: "Request failed",
    },
    footer: {
      privacy: "Your key stays in this browser. Requests go from your machine to OpenRouter.",
      pricing: "Output is free: US$ 0.042 per million input tokens.",
      notAffiliated: "Independent community tool. Not affiliated with TypeSafe AI or OpenRouter.",
    },
  },

  pt: {
    app: {
      name: "Jev Playground",
      tagline: "Decisões tipadas em milissegundos",
      subtitle:
        "Monte um estado e perguntas tipadas, execute contra o modelo Jev System One via OpenRouter e leia probabilidades calibradas com latência, tokens e custo.",
    },
    top: {
      langLabel: "Idioma",
      langEn: "EN",
      langPt: "PT",
      github: "Código",
      docs: "Docs do Jev",
      keyBadge: "Chave",
      noKey: "Sem chave",
    },
    gate: {
      title: "Conecte sua chave do OpenRouter",
      sub: "Cole uma chave para liberar o playground. Ela é validada no OpenRouter e fica só neste navegador.",
      label: "Chave de API do OpenRouter",
      placeholder: "sk-or-v1-…",
      validate: "Validar chave",
      validating: "Validando…",
      openrouterLink: "Crie uma chave em openrouter.ai/keys",
      safety: "Crie uma chave com limite de crédito. Nunca reutilize aqui uma chave de produção.",
      stored: "Guardada apenas no localStorage. Nada sai daqui exceto para o OpenRouter.",
      errorInvalid: "O OpenRouter rejeitou esta chave. Confira e tente de novo.",
      errorNetwork: "Não foi possível falar com o endpoint de chave. Tente em instantes.",
      errorEmpty: "Digite uma chave primeiro (começa com sk-or-v1-).",
      connected: "Chave conectada",
      continueAnyway: "Pular validação e abrir o editor",
    },
    keyStatus: {
      label: "Rótulo",
      remaining: "Crédito restante",
      limit: "Limite de crédito",
      usage: "Consumo",
      freeTier: "Tier gratuito",
      yes: "sim",
      no: "não",
      unlimited: "ilimitado",
      change: "Trocar chave",
      forget: "Esquecer chave",
    },
    builder: {
      stateTitle: "Estado",
      stateHint: "O conteúdo a julgar: uma mensagem, ticket, log ou objeto JSON.",
      stateModeText: "Texto",
      stateModeJson: "JSON",
      statePlaceholderText: "O checkout mostra tela branca após clicar em Pagar.",
      statePlaceholderJson: '{\n  "ticket": "O checkout mostra tela branca após clicar em Pagar.",\n  "canal": "email"\n}',
      questionsTitle: "Perguntas",
      questionsHint: "Todas correm em paralelo contra o mesmo estado. Separe perguntas compostas.",
      addNoul: "Adicionar sim/não",
      addChoice: "Adicionar escolha",
      addScore: "Adicionar nota",
      emptyTitle: "Nenhuma pergunta ainda",
      emptyBody: "Adicione uma pergunta sim/não, escolha ou nota para obter uma decisão.",
      qId: "Chave",
      qIdHint: "Id da resposta. Em branco usa q1, q2…",
      qInstructions: "Pergunta",
      qInstructionsPlaceholderNoul: "O cliente relata um defeito?",
      qInstructionsPlaceholderChoice: "Que equipa deve tratar?",
      qInstructionsPlaceholderScore: "Quão urgente é isto?",
      noulName: "Sim / Não (noul)",
      noulDesc: "Probabilidade de sim, de 0 a 1.",
      choiceName: "Escolha (choice)",
      choiceDesc: "Uma opção entre até 255, com distribuição completa.",
      scoreName: "Nota (score)",
      scoreDesc: "Régua ordenada de 2 a 10 níveis, média ponderada.",
      criteriaOptional: "Critérios (opcional)",
      criteriaTrue: "Perto de 1 significa",
      criteriaFalse: "Perto de 0 significa",
      criteriaOption: "Rubrica de",
      optionKey: "Opção",
      optionRubric: "Rubrica (opcional)",
      addOption: "Adicionar opção",
      removeOption: "Remover opção",
      levels: "Níveis (do menor ao maior)",
      levelPlaceholder: "Bloqueia receita agora",
      addLevel: "Adicionar nível",
      removeLevel: "Remover nível",
      removeQuestion: "Remover pergunta",
      advancedTitle: "Avançado",
      modelLabel: "Modelo",
      sessionId: "session_id (opcional)",
      sessionIdHint: "Agrupa requisições em observabilidade. Máx. 256 caracteres.",
      userId: "user (opcional)",
      userIdHint: "Id do usuário final para observabilidade. Máx. 256 caracteres.",
    },
    issues: {
      title: "Verificação do request",
      clean: "Pronto para executar",
      errors: "erros",
      warnings: "avisos",
      tips: "dicas",
      stateEmpty: "O estado está vazio. Adicione o conteúdo que o modelo deve julgar.",
      stateInvalidJson: "O estado não é JSON válido. Corrija a sintaxe ou volte ao modo Texto.",
      stateTooLarge: "O estado passa do orçamento de 32k tokens (estado + pergunta maior). Enxugue.",
      stateRot: "Estados grandes com detalhe irrelevante pioram a precisão. Guarde só o que importa.",
      noQuestions: "Adicione pelo menos uma pergunta.",
      duplicateId: "Chave de resposta repetida: \"{{id}}\". As chaves devem ser únicas.",
      instructionsEmpty: "O texto da pergunta está vazio.",
      asksForText: "O Jev nunca gera texto. Transforme a expectativa numa escolha entre opções listadas.",
      compoundQuestion: "Duas perguntas numa linha. Separe: correm em paralelo sem custo de latência.",
      mathOrDates: "Isto parece conta, matemática ou datas. Calcule em código e leve o resultado no estado.",
      choiceNoOptions: "Escolha precisa de pelo menos uma opção.",
      choiceTooMany: "Escolha aceita no máximo {{max}} opções.",
      choiceDuplicateOption: "Opção repetida. As chaves de opção devem ser únicas.",
      choiceNoExit: "Considere uma opção \"other\"/\"none\" para o modelo não ser forçado a classe errada.",
      scoreLevelCount: "Nota precisa de entre {{min}} e {{max}} níveis ordenados.",
      scoreNumericLevels: "Níveis numéricos têm desempenho péssimo. Descreva uma situação concreta por nível.",
    },
    run: {
      run: "Executar decisões",
      running: "Executando…",
      again: "Executar de novo",
      needsKey: "Conecte uma chave para executar",
      fixErrors: "Corrija os erros para executar",
      thresholdNote: "Bandas: auto a partir de 0,90; revisão humana de 0,50 a 0,89; abstém-se abaixo de 0,50.",
    },
    results: {
      title: "Decisões",
      emptyTitle: "Ainda sem execução",
      emptyBody: "Execute o request para ver respostas tipadas, distribuições e confiança.",
      decision: "Decisão",
      probability: "Probabilidade de sim",
      confidence: "Confiança",
      certainty: "Certeza",
      confidenceNote: "A confiança descreve a distribuição, não garante que a resposta esteja certa.",
      weighted: "Nota ponderada",
      distribution: "Distribuição",
      rawAnswer: "Resposta bruta",
      bandAuto: "auto",
      bandHitl: "revisão",
      bandAbstain: "abster",
      bandAutoHint: "Confiança a partir de 0,90: seguro agir automaticamente.",
      bandHitlHint: "Confiança de 0,50 a 0,89: confirme com um humano antes de agir.",
      bandAbstainHint: "Abaixo de 0,50: não aja. Escale para um modelo mais lento e profundo.",
    },
    metrics: {
      title: "Métricas",
      latency: "Latência",
      inputTokens: "Tokens de entrada",
      outputTokens: "Tokens de saída",
      cost: "Custo",
      perDecision: "Por decisão",
      throughput: "Vazão",
      resolvedModel: "Modelo resolvido",
      provider: "Provider",
      generationId: "Id da geração",
      questionCount: "Perguntas",
      history: "Histórico",
      historyHint: "Últimas execuções neste navegador. Barras de latência, mais recente primeiro.",
      clearHistory: "Limpar",
      noHistory: "Nenhuma execução registrada ainda.",
      stats: "Estatísticas da geração",
      statsFetch: "Buscar estatísticas",
      statsHint: "Lê GET /api/v1/generation com o id do corpo da resposta.",
    },
    inspector: {
      title: "Request",
      hint: "Corpo JSON, modelo do request, cURL e exportação Postman do request exato.",
      tabBody: "Corpo JSON",
      tabModel: "Modelo do request",
      tabCurl: "cURL",
      tabPostman: "Postman",
      copy: "Copiar",
      copied: "Copiado",
      download: "Baixar coleção",
      postmanHint: "Importa no Postman como coleção v2.1. A chave vai como variável {{openrouter_api_key}}.",
      curlHint: "Usa a variável de ambiente OPENROUTER_API_KEY.",
      modelIntro: "POST para o endpoint Decisions. Cada campo abaixo é o que este playground envia.",
      modelFields: [
        { field: "model", desc: "typesafe/jev-1.13 ou o alias ~typesafe/jev-latest." },
        { field: "state", desc: "string, objeto ou array de texto. Julgado uma vez, compartilhado por todas as perguntas." },
        { field: "questions", desc: "Mapa de id para pergunta. Todas avaliadas em paralelo." },
        { field: "questions.*.type", desc: "noul (probabilidade de sim), choice (uma entre N), score (nível ponderado)." },
        { field: "questions.*.instructions", desc: "A pergunta completa. A chave do mapa nunca chega ao modelo." },
        { field: "questions.*.criteria", desc: "noul: {true, false} opcionais. choice: opção para rubrica (string ou null). score: 2 a 10 descrições ordenadas de nível." },
        { field: "session_id", desc: "Opcional, máx. 256 caracteres. Agrupa requisições em observabilidade." },
        { field: "user", desc: "Opcional, máx. 256 caracteres. Id do usuário final para observabilidade." },
      ],
    },
    errors: {
      network: "Erro de rede. Repita, ou veja se um proxy/extensão está bloqueando a chamada.",
      e400: "Request inválido. A mensagem aponta o campo a corrigir.",
      e401: "Chave em falta ou inválida. Confira sua chave do OpenRouter.",
      e402: "Créditos insuficientes. Recarregue em openrouter.ai/credits.",
      e403: "Proibido para esta chave.",
      e404: "Não encontrado. Confira o id do modelo.",
      e413: "Payload grande demais. Reduza o estado.",
      e422: "Falha de validação.",
      e429: "Rate limit. Aguarde um pouco e repita.",
      e5xx: "OpenRouter ou TypeSafe sobrecarregado. Repita em instantes.",
      generic: "O request falhou",
    },
    footer: {
      privacy: "Sua chave fica neste navegador. Os requests saem da sua máquina para o OpenRouter.",
      pricing: "Saída é gratuita: US$ 0,042 por milhão de tokens de entrada.",
      notAffiliated: "Ferramenta comunitária independente. Sem afiliação com TypeSafe AI ou OpenRouter.",
    },
  },
};

export type Dict = (typeof dict)["en"];